# This is a basic workflow to help you get started with Actions

name: deploy to azure

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*", "*.ps1"]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        name: checkout files
      - name: do a bicep linter tes
        run: az bicep build --file storage.bicep 
        
  deploy:
    runs-on: ubuntu-latest
    env: 
      AZ_RG_Name: RG11
    needs: [lint]
    steps: 
      - uses: actions/checkout@v3
        name: checkout files
      - uses: azure/login@v1
        name: sign in
        with:
          creds: ${{secrets.AZ_CREDS}}
      - uses: azure/cli@v1
        name: create rg
        with:
          inlineScript: |
            az group create --name ${{env.AZ_RG_Name}} --location westeurope
      - uses: azure/arm-deploy@v1
        name: deploy storage
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          template: ./storage.bicep
          resourceGroupName: ${{env.AZ_RG_Name}}
      - name: display sa name
        run: |
          echo ${{steps.deploy-sa.outputs.mysaname}}
    