# This is a basic workflow to help you get started with Actions

name: deploy to azure

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*", "*.ps1"]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        name: checkout files
      - name: do a bicep linter tes
        run: az bicep build --file storage.bicep  
    